namespace Game.City;

public enum CityModifierType
{
	Attractiveness = 0,
	CrimeAccumulation = 1,
	DisasterWarningTime = 3,
	DisasterDamageRate = 4,
	DiseaseProbability = 5,
	ParkEntertainment = 6,
	CriminalMonitorProbability = 7,
	IndustrialAirPollution = 8,
	IndustrialGroundPollution = 9,
	IndustrialGarbage = 10,
	RecoveryFailChange = 11,
	OreResourceAmount = 12,
	OilResourceAmount = 13,
	UniversityInterest = 14,
	OfficeSoftwareDemand = 15,
	IndustrialElectronicsDemand = 16,
	OfficeSoftwareEfficiency = 17,
	IndustrialElectronicsEfficiency = 18,
	TelecomCapacity = 19,
	Entertainment = 20,
	HighwayTrafficSafety = 21,
	PrisonTime = 22,
	CrimeProbability = 23,
	CollegeGraduation = 24,
	UniversityGraduation = 25,
	ImportCost = 26,
	LoanInterest = 27,
	BuildingLevelingCost = 28,
	ExportCost = 29,
	TaxiStartingFee = 30,
	IndustrialEfficiency = 31,
	OfficeEfficiency = 32,
	PollutionHealthAffect = 33,
	HospitalEfficiency = 34,
	IndustrialFishInputEfficiency = 35,
	IndustrialFishHubEfficiency = 36,
	CityServiceImportCost = 37,
	CityServiceBuildingBaseUpkeepCost = 38,
	CrimeResponseTime = 39,
	TaxHappiness = 40
}
