namespace Game.Prefabs;

public enum BuildingType
{
	None = -1,
	Hospital,
	PowerPlant,
	Transformer,
	FreshWaterBuilding,
	SewageBuilding,
	StormWaterBuilding,
	TransportDepot,
	TransportStation,
	GarbageFacility,
	FireStation,
	PoliceStation,
	RoadMaintenanceDepot,
	PostFacility,
	TelecomFacility,
	School,
	EmergencyShelter,
	DisasterFacility,
	FirewatchTower,
	Park,
	DeathcareFacility,
	Prison,
	AdminBuilding,
	WelfareOffice,
	ResearchFacility,
	ParkMaintenanceDepot,
	CarParkingFacility,
	Battery,
	ResidentialBuilding,
	CommercialBuilding,
	IndustrialBuilding,
	OfficeBuilding,
	SignatureResidential,
	ExtractorBuilding,
	SignatureCommercial,
	SignatureIndustrial,
	SignatureOffice,
	LandValueSources,
	BicycleParkingFacility
}
