using Game.UI.Editor;

namespace Game.Prefabs;

public enum NetPieceRequirements
{
	[HideInEditor]
	Node,
	[HideInEditor]
	Intersection,
	[HideInEditor]
	DeadEnd,
	[HideInEditor]
	Crosswalk,
	[HideInEditor]
	BusStop,
	[HideInEditor]
	Median,
	[HideInEditor]
	TrainStop,
	[HideInEditor]
	OppositeTrainStop,
	[HideInEditor]
	Inverted,
	[HideInEditor]
	TaxiStand,
	[HideInEditor]
	LevelCrossing,
	Elevated,
	[HideInEditor]
	Tunnel,
	[HideInEditor]
	Raised,
	[HideInEditor]
	Lowered,
	[HideInEditor]
	LowTransition,
	[HideInEditor]
	HighTransition,
	[HideInEditor]
	WideMedian,
	[HideInEditor]
	TramTrack,
	[HideInEditor]
	TramStop,
	[HideInEditor]
	OppositeTramTrack,
	[HideInEditor]
	OppositeTramStop,
	[HideInEditor]
	MedianBreak,
	[HideInEditor]
	ShipStop,
	[HideInEditor]
	Sidewalk,
	[HideInEditor]
	Edge,
	[HideInEditor]
	SubwayStop,
	[HideInEditor]
	OppositeSubwayStop,
	[HideInEditor]
	MiddlePlatform,
	[HideInEditor]
	Underground,
	[HideInEditor]
	Roundabout,
	[HideInEditor]
	OppositeSidewalk,
	[HideInEditor]
	SoundBarrier,
	[HideInEditor]
	Overhead,
	[HideInEditor]
	TrafficLights,
	[HideInEditor]
	PublicTransportLane,
	[HideInEditor]
	OppositePublicTransportLane,
	[HideInEditor]
	Spillway,
	[HideInEditor]
	MiddleGrass,
	[HideInEditor]
	MiddleTrees,
	[HideInEditor]
	WideSidewalk,
	[HideInEditor]
	SideGrass,
	[HideInEditor]
	SideTrees,
	[HideInEditor]
	OppositeGrass,
	[HideInEditor]
	OppositeTrees,
	[HideInEditor]
	Opening,
	[HideInEditor]
	Front,
	[HideInEditor]
	Back,
	[HideInEditor]
	Flipped,
	RemoveTrafficLights,
	[HideInEditor]
	AllWayStop,
	[HideInEditor]
	Pavement,
	[HideInEditor]
	Gravel,
	[HideInEditor]
	Tiles,
	ForbidLeftTurn,
	ForbidRightTurn,
	[HideInEditor]
	OppositeWideSidewalk,
	OppositeForbidLeftTurn,
	OppositeForbidRightTurn,
	[HideInEditor]
	OppositeSoundBarrier,
	[HideInEditor]
	SidePlatform,
	[HideInEditor]
	AddCrosswalk,
	RemoveCrosswalk,
	[HideInEditor]
	Lighting,
	[HideInEditor]
	OppositeBusStop,
	[HideInEditor]
	OppositeTaxiStand,
	[HideInEditor]
	OppositeRaised,
	[HideInEditor]
	OppositeLowered,
	[HideInEditor]
	OppositeLowTransition,
	[HideInEditor]
	OppositeHighTransition,
	[HideInEditor]
	OppositeShipStop,
	[HideInEditor]
	OppositePlatform,
	[HideInEditor]
	OppositeAddCrosswalk,
	[HideInEditor]
	OppositeRemoveCrosswalk,
	[HideInEditor]
	Inside,
	ForbidStraight,
	OppositeForbidStraight,
	[HideInEditor]
	Hidden,
	[HideInEditor]
	ParkingSpaces,
	[HideInEditor]
	OppositeParkingSpaces,
	[HideInEditor]
	FixedNodeSize,
	[HideInEditor]
	HalfLength,
	AbruptEnd,
	OppositeAbruptEnd,
	[HideInEditor]
	AttachmentTrack,
	EnterGate,
	ExitGate,
	[HideInEditor]
	StyleBreak,
	[HideInEditor]
	FerryStop,
	[HideInEditor]
	StraightNodeEnd,
	[HideInEditor]
	BicycleLane,
	[HideInEditor]
	OppositeBicycleLane,
	[HideInEditor]
	ForbidBicycles,
	[HideInEditor]
	OppositeForbidBicycles
}
